---
- hosts: all
  
  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
      register: apt_upgrade_result

  post_tasks:
    - name: Send notification
      ansible.builtin.shell: |
        curl -d "Host: {{ inventory_hostname }}, Result: {{ apt_upgrade_result.stdout }}" ntfy.tshome.camdvr.org/tshome
      register: curl_result

    - name: Display curl result
      debug:
        var: curl_result.stdout